config/routes.rb
Rails.application.routes.draw do

   root 'saudas#index'

   resources :saudas do
    resources :orders
  end
 

   resources :customers

   resources :categories

   

 

   resources :sauda_line_items

   resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :order_rates
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :customer
	belongs_to :sauda
	has_many :order_products
	has_many :order_rates
	accepts_nested_attributes_for :order_products

	before_save :generate_initial_order_details


	def generate_initial_order_details
		
		if Order.exists?
			order = Order.order(:id).last
			self.order_number = "NTPLO - #{order.id + 1}"
		else
			self.order_number = "NTPLO - 1"
		end

		#self.sauda.is_order_taken = true

		#self.customer_id = @sauda.customer_id
		#self.sauda_id = @sauda.id
		self.order_date = Date.today
	end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
end

app/models/order_rate.rb
class OrderRate < ActiveRecord::Base
	belongs_to :order
	belongs_to :category
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :order_products
	belongs_to :category
end

app/models/sauda.rb
class Sauda < ActiveRecord::Base
	belongs_to :customer
	has_one :order
	has_many :sauda_line_items
	accepts_nested_attributes_for :sauda_line_items


	before_save :generate_initial_sauda_details

	def generate_initial_sauda_details
		
		if Sauda.exists?
			sauda = Sauda.order(:id).last
			self.sauda_number = "NTPL - #{sauda.id + 1}"
		else
			self.sauda_number = "NTPL - 1"
		end

		self.sauda_date = Date.today
	end

	def update_sauda_order()
		self.update_attributes(:is_order_taken => true)
	end

end

app/models/sauda_line_item.rb
class SaudaLineItem < ActiveRecord::Base
	belongs_to :sauda
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			#redirect_to root_path, notice: "Successfully created Order"
			redirect_to category_path(@category), notice: "Successfully added Category"
		

		end
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
	end

	private

	def category_params
		params[:category].permit(:name)
		# Protecting from mass assignment - which is a security feature.
	end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.all
	end



	def create
		@customer = Customer.new(customer_params)
		if @customer.save
			#redirect_to root_path, notice: "Successfully created Order"
			redirect_to customer_path(@customer), notice: "Successfully added Customer"
		

		end
	end

	def new
		@customer = Customer.new
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def destroy
		@customer = Customer.find(params[:id])
		@customer.destroy
		redirect_to customers_path, notice: "Customer #{@customer.id} successfully deleted"
	end

	private

	def customer_params
		params[:customer].permit(:customer_name, :phone_no, :location)
		# Protecting from mass assignment - which is a security feature.
	end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
		@orders = Order.all
	end

	def create
		


		params[:order][:order_products_attributes].each do |layer_number, subparams|
			#binding.pry
			if(subparams[:product_id] == "")
  				params[:order][:order_products_attributes].delete(layer_number)
  			end
  		end

		@sauda = Sauda.find(params[:sauda_id])
		@order = Order.new(order_params)


		@order.customer_id = @sauda.customer_id
		@order.sauda_id = @sauda.id

		@order.total = 0
  		
		@order.order_products.each do |order_product|
			#This will update the price of each orderitem by extracting the rate from the respective sauda line item
			#ToDo: The logic here may need to be modified for nails since depending on the sauda rate, the price is different for different sizes
			order_product[:price] = @sauda.sauda_line_items.find_by(category_id: order_product.product.category[:id])[:rate]
			@order.total += order_product[:order_quantity] * order_product[:price]	
		end

		#binding.pry
		if @order.save
			#redirect_to root_path, notice: "Successfully created Order"
			@sauda.update_sauda_order
			redirect_to sauda_order_path(@sauda, @order), notice: "Successfully added Order"
		end
	end

	def new
		@sauda = Sauda.find(params[:sauda_id])
		@order = Order.new
		@sauda_line_items = @sauda.sauda_line_items
		@order.order_products.build
	end

	def show
		@order = Order.find(params[:id])
	end

	private

	def order_params
		params[:order].permit(:sauda_id, :customer_id, order_products_attributes: [:order_id, :product_id, :order_quantity])
	end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			#redirect_to root_path, notice: "Successfully created Order"
			redirect_to category_path(@product.category_id), notice: "Successfully added Product to Category"
		end
	end

	def new
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
	end

	private

	def product_params
		params[:product].permit(:size, :category_id)
		# Protecting from mass assignment - which is a security feature.
	end

end

app/controllers/saudas_controller.rb
class SaudasController < ApplicationController
	
	def index
		@saudas = Sauda.all
	end

	def new
		@sauda = Sauda.new
		
		#This is to allow nested parameters forms from within the Sauda Form
		#So this allows sauda
		Category.count.times {@sauda.sauda_line_items.build}
		#binding.pry
	end

	def create
		
		#Not all ProductCategories will have a Sauda, hence some will be left blank 
      	#This will ensure that all those blank values do not get udated in the Database
      	params[:sauda][:sauda_line_items_attributes].each do |layer_number, subparams|
  			if(subparams[:category_id] == "")
  				params[:sauda][:sauda_line_items_attributes].delete(layer_number)
  			end
  		end
      	
      	#binding.pry
		@sauda = Sauda.new(sauda_params)
		#binding.pry
		if(@sauda.save)
			redirect_to sauda_path(@sauda), notice: "Successfully added Sauda"
		end


	end

	def show
		@sauda = Sauda.find(params[:id])
	end

	private

	def sauda_params
		params[:sauda].permit(:customer_id, :is_order_taken, :is_delivered, sauda_line_items_attributes: [:category_id, :rate, :quantity] )
		# Protecting from mass assignment - which is a security feature.
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sauda_line_items_helper.rb
module SaudaLineItemsHelper
end

app/helpers/saudas_helper.rb
module SaudasHelper
end

app/views/categories/index.html.erb
<h2> All Categories </h2>

	<% if @categories.empty? %>
	<p>You do not have any Categories, Create your first product category"</p>  <%= link_to "New Product Category", new_category_path %>


	<%else%>
		<table border = "1">
			<thead>
				<tr>
					<th>#</th>
					<th>Product Category</th>
					<th>Delete Category</th>
				</tr>
		
			</thead>
			
			<tbody>
				<% @categories.each_with_index do |category,index| %>
				<tr>
					<td> <%= index + 1 %> </td>
					<td> <%= category.name %> </td>
					<td> <%=link_to "remove", category, method: :delete, data: {confirm: "Are You Sure"} %> </td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<br/>
		
	<%end%>

	<!--link_to("Show All Orders", )-->

app/views/categories/new.html.erb
 <b>Add Product Category</b>

<%= form_for @category do |f| %>
	
	<%= f.label :ProductCategoryName %><br/>
	<%= f.text_field :name %><br/>
	
	<%= f.submit %>
<%end%>

app/views/categories/show.html.erb
<H2> Product Category and Sizes </H2>

<p> Product Category Name : <%= @category.name %></p>



	<table border = "1">
		<thead>
			<tr>
				<th>#</th>
				<th>Category</th>
				<th>Size</th>
			</tr>
		
		</thead>

		<tbody>
		<% Product.where(category_id: @category.id).each_with_index do |product,index| %>
 			<tr>
				<td> <%= index + 1 %> </td>
				<td> <%= product.category.name%> </td>
				<td> <%= product.size %> </td>
			</tr>
		</tbody>
<%end%>

app/views/customers/index.html.erb
<h2> All Customers </h2>

	<% if @customers.empty? %>
	<p>You do not have any Customers, Create your first customer"</p>  <%= link_to "New Customer", new_customer_path %>


	<%else%>
		<table border = "1">
			<thead>
				<tr>
					<th>#</th>
					<th>Customer ID</th>
					<th>Customer_Name</th>
					<th>Phone_No</th>
					<th>Customer Location</th>
					<th>Delete Customer</th>
				</tr>
		
			</thead>
			
			<tbody>
				<% @customers.each_with_index do |customer,index| %>
				<tr>
					<td> <%= index + 1 %> </td>
					<td> <%= customer.id %> </td>
					<td> <%= customer.customer_name %> </td>
					<td> <%= customer.phone_no %> </td>
					<td> <%= customer.location %> </td>
					<td> <%=link_to "remove", customer, method: :delete, data: {confirm: "Are You Sure"} %> </td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<br/>
		
	<%end%>

	<!--link_to("Show All Orders", )-->

app/views/customers/new.html.erb
 <b>Add Customer details</b>

<%= form_for @customer do |f| %>
	
	<%= f.label :CustomerName %><br/>
	<%= f.text_field :customer_name %><br/>
	
	<%= f.label :PhoneNo %><br/>
	<%= f.text_field :phone_no %><br/>

	<%= f.label :Location %><br/>
	<%= f.text_field :location %><br/>

	<%= f.submit %>
<%end%>

app/views/customers/show.html.erb
<H2> Thank You for adding Customer </H2>

<p> Customer Name : <%= @customer.customer_name %></p>
<p> Location : <%= @customer.location%></p>
<p> Phone No : <%= @customer.phone_no%></p>

 	

app/views/orders/index.html.erb
<h2> All Orders </h2>

	<% if @orders.empty? %>
	<p>You do not have any orders, Create your first order"</p>  <%= link_to "New Order", new_order_path %>


	<%else%>
		<table border = "1">
			<thead>
				<tr>
					<th>#</th>
					<th>Order_Number</th>
					<th>Customer_Name</th>
					<th>Total</th>
				</tr>
		
			</thead>
			
			<tbody>
				<% @orders.each_with_index do |order,index| %>
				<tr>
					<td> <%= index + 1 %> </td>
					<td> <%= link_to(order.order_number, order_path(order)) %></td>
					<td> <%= order.customer_name %></td>
					<td> <%= order.total %> </td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<br/>
		
	<%end%>

	<!--link_to("Show All Orders", )-->

app/views/orders/new.html.erb
<%= link_to "Add Customer", new_customer_path %> | <%= link_to "Add Product Category", new_category_path %>

<%= form_for [@sauda, @order] do |f| %>
	
	<%= f.label :Customer %><br/>
	<%= @sauda.customer.customer_name %><br/>

	<% hidden_field :customer_id, @sauda.customer_id %>

	<%= f.label :SaudaDate %><br/>
	<%= @sauda.sauda_date %><br/>
	
	<% @sauda.sauda_line_items.each do |item|%>
		<%= item.category.name%>
		<%= item.rate%>
		<%= item.quantity%>

		<% item.category.products.each do |product| %>

			<%= f.fields_for :order_products do |order_product|%>
				<%= order_product.label :size %>
				<%= order_product.collection_select  :product_id, item.category.products, :id, :size, prompt: "Select Product" %><br/>
				<%= order_product.label :quantity %>
				<%= order_product.number_field :order_quantity %> <br/>
			<%end%>

		<%end%>		

	<%end%>	

	<%= f.submit %>
<%end%>

app/views/orders/show.html.erb
<H2> Order Placed </H2>
<p> Sauda Number : <%= @order.sauda[:sauda_number] %></p>
<p> Sauda Date : <%= @order.sauda[:sauda_date].strftime("%d %B %Y") %></p>
<p> Order Number : <%= @order.order_number %></p>
<p> Order Date : <%= @order.order_date.strftime("%d %B %Y") %></p>
<!--<p> Your Order Date : <%= @order.order_date %></p>-->
 	<H2> Your Orders</H2>
 	<table border = "1">
 	
		<thead>
			<tr>
				<th>#</th>
				<th>Product</th>
				<th>Size</th>
				<th>Quantity</th>
				<th>Price</th>
			</tr>
		
		</thead>
		<tbody>
		<% @order.order_products.each_with_index do |line_item,index| %>
		
			<tr>
				<td> <%= index + 1 %> </td>

				<td> <%= line_item.product.category[:name] %> </td>
				<td> <%= line_item.product[:size] %> </td>
				<td> <%= line_item.order_quantity %> </td>
				<td> <%= line_item.price %> </td>

			</tr>
		<%end %>

		</tbody>
	</table>

	<H3> Total Order Value = <%= @order[:total] %></H3>

app/views/products/index.html.erb
<h2> All Products </h2>

	<% if @products.empty? %>
	<p>You do not have any products, Create your first prodcut"</p>  <%= link_to "New Product", new_product_path %>


	<%else%>
		<table border = "1">
			<thead>
				<tr>
					<th>#</th>
					<th>ProductCategory</th>
					<th>Size</th>
				</tr>
		
			</thead>
			
			<tbody>
				<% @products.each_with_index do |product,index| %>
				<tr>
					<td> <%= index + 1 %> </td>
					<td> <%= product.category.name %></td>
					<td> <%= product.size %></td>
					
				</tr>
				<% end %>
			</tbody>
		</table>
		<br/>
		
	<%end%>

	<!--link_to("Show All Orders", )-->

app/views/products/new.html.erb
 <b>Add Product Size</b>

<%= form_for @product do |f| %>
	
	<%= f.label :ProductCategory %><br/>
	<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>
		
	<%= f.label :ProductSize %><br/>
	<%= f.text_field :size %><br/>
	
	<%= f.submit %>
<%end%>

app/views/saudas/index.html.erb
<h2> All Saudas </h2>

	<% if @saudas.empty? %>
	<p>You do not have any saudas, Create your first sauda"</p>  <%= link_to "New Sauda", new_sauda_path %>


	<%else%>
		<table border = "1">
			<thead>
				<tr>
					<th>#</th>
					<th>Sauda_Number</th>
					<th>Customer_Name</th>
					<th>Location</th>
					<th>OrderTaken</th>
					<th>OrderDelivered</th>
				</tr>
		
			</thead>
			
			<tbody>
				<% @saudas.each_with_index do |sauda,index| %>
				<tr>
					<td> <%= index + 1 %> </td>
					<td> <%= link_to(sauda.sauda_number, sauda_path(sauda)) %></td>
					<td> <%= sauda.customer.customer_name %></td>
					<td> <%= sauda.customer.location %></td>
					<td> <%= if sauda.is_order_taken == false  then link_to "Take Order", new_sauda_order_path(sauda) else "Yes" end%> 
					</td>
					<td> <%= if sauda.is_delivered == false  then "Delivery Details" else "Delivered" end%></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<br/>
		
	<%end%>

	<!--link_to("Show All Orders", )-->

app/views/saudas/new.html.erb
<%= form_for @sauda do |f| %>
	
	<%= f.label :Customer %><br/>
	<%= f.collection_select :customer_id, Customer.all, :id, :customer_name, prompt: "Select Customer" %><br/>


	Products:
	
	<%= f.fields_for :sauda_line_items do |sauda_line_item|%>
		
		
			<%= sauda_line_item.label :ProductCategory %><br/>
			<%= sauda_line_item.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>
		
			<%= sauda_line_item.label :Quantity %> <br/>
			<%= sauda_line_item.number_field :quantity %> <br/>
		
			<%= sauda_line_item.label :Rate %> <br/>
			<%= sauda_line_item.number_field :rate %> <br/>
		

	<%end%>

	
	
	<%= f.submit %>

<%end%>

app/views/saudas/show.html.erb
<H2> Sauda has been placed </H2>

<p> Sauda Number : <%= @sauda.sauda_number %></p>
<p> Sauda Date : <%= @sauda.sauda_date.strftime("%d %B %Y") %></p>
<p> Customer Name : <%= @sauda.customer.customer_name %></p>


<H2> Sauda Details</H2>

<table border = "1">
		<thead>
			<tr>
				<th>#</th>
				<th>Product</th>
				<th>Price</th>
				<th>Quantity</th>
				<th>Total</th>
				<th>Actions</th>
			</tr>
		
		</thead>
		<tbody>
 	<% @sauda.sauda_line_items.each_with_index do |sauda_line_item,index| %>
			<tr>
				<td> <%= index + 1 %> </td>
				<td> <%= sauda_line_item.category.name%> </td>
				<td> <%= sauda_line_item.rate %> </td>
				<td> <%= sauda_line_item.quantity %></td>
			</tr>
		</tbody>
	<%end %>

 	